LOAD DATA LOCAL INFILE 'Uniq_SellersInf.txt' INTO TABLE SellersInf FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'ItemsInf.txt' INTO TABLE ItemsInf FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'ItemsCat.txt' INTO TABLE ItemsCat FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'Uniq_BiddersInf.txt' INTO TABLE BiddersInf FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'ItemsBid.txt' INTO TABLE ItemsBid FIELDS TERMINATED BY '|*|';




